name: Daily Job Scraper

on:
  schedule:
    # Runs at 16:00 UTC (12:00 PM EDT) every day
    - cron: '0 16 * * *'
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        include:
          - profile_name: "Tech Jobs for Daudi"
            # Just put the name of the secret as a text string here!
            recipient_secret_name: "EMAIL_A_RECIPIENT"
            keywords: '["software engineer","software developer","backend engineer","frontend engineer","full stack engineer","data engineer","junior developer","associate software engineer","data scientist","AI Engineer"]'
          
          - profile_name: "Business Jobs for Adi"
            recipient_secret_name: "EMAIL_B_RECIPIENT"
            keywords: '["data analyst","underwriter","data entry","admin assistant","business analyst","project manager","project coordinator","insurance"]'

          - profile_name: "Tech Jobs for Roscoe"
            recipient_secret_name: "EMAIL_C_RECIPIENT"
            keywords: '["software engineer", "data analyst", "IT", "project manager","project coordinator", "software developer","backend engineer","frontend engineer","full stack engineer","data engineer","junior developer","associate software engineer","data scientist","AI Engineer"]'

    name: Run for ${{ matrix.profile_name }}
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
      
      - name: Install Dependencies
        run: |
          pip install requests beautifulsoup4 selenium webdriver-manager python-dotenv python-jobspy

      - name: Run Scraper Script
        env:
          # Use bracket notation to dynamically fetch the secret based on the matrix string!
          EMAIL_RECIPIENT: ${{ secrets[matrix.recipient_secret_name] }}
          KEYWORDS: ${{ matrix.keywords }}
          
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          ADZUNA_APP_ID: ${{ secrets.ADZUNA_APP_ID }}
          ADZUNA_APP_KEY: ${{ secrets.ADZUNA_APP_KEY }}
          USAJOBS_API_KEY: ${{ secrets.USAJOBS_API_KEY }}
          HANDSHAKE_EMAIL: ${{ secrets.HANDSHAKE_EMAIL }}
          HANDSHAKE_PASSWORD: ${{ secrets.HANDSHAKE_PASSWORD }}
          USAJOBS_USER_AGENT: ${{ secrets.USAJOBS_USER_AGENT }}
        run: python job_alert.py
